/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as ApiModelsRouteImport } from './routes/api/models'
import { Route as ApiDevicesRouteImport } from './routes/api/devices'
import { Route as ApiOutputJobIdRouteImport } from './routes/api/output.$jobId'
import { Route as ApiJobsJobIdRouteImport } from './routes/api/jobs.$jobId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiModelsRoute = ApiModelsRouteImport.update({
  id: '/api/models',
  path: '/api/models',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDevicesRoute = ApiDevicesRouteImport.update({
  id: '/api/devices',
  path: '/api/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOutputJobIdRoute = ApiOutputJobIdRouteImport.update({
  id: '/api/output/$jobId',
  path: '/api/output/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsJobIdRoute = ApiJobsJobIdRouteImport.update({
  id: '/api/jobs/$jobId',
  path: '/api/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/devices': typeof ApiDevicesRoute
  '/api/models': typeof ApiModelsRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/jobs/$jobId': typeof ApiJobsJobIdRoute
  '/api/output/$jobId': typeof ApiOutputJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/devices': typeof ApiDevicesRoute
  '/api/models': typeof ApiModelsRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/jobs/$jobId': typeof ApiJobsJobIdRoute
  '/api/output/$jobId': typeof ApiOutputJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/devices': typeof ApiDevicesRoute
  '/api/models': typeof ApiModelsRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/jobs/$jobId': typeof ApiJobsJobIdRoute
  '/api/output/$jobId': typeof ApiOutputJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/devices'
    | '/api/models'
    | '/api/upload'
    | '/api/jobs/$jobId'
    | '/api/output/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/devices'
    | '/api/models'
    | '/api/upload'
    | '/api/jobs/$jobId'
    | '/api/output/$jobId'
  id:
    | '__root__'
    | '/'
    | '/api/devices'
    | '/api/models'
    | '/api/upload'
    | '/api/jobs/$jobId'
    | '/api/output/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiDevicesRoute: typeof ApiDevicesRoute
  ApiModelsRoute: typeof ApiModelsRoute
  ApiUploadRoute: typeof ApiUploadRoute
  ApiJobsJobIdRoute: typeof ApiJobsJobIdRoute
  ApiOutputJobIdRoute: typeof ApiOutputJobIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/models': {
      id: '/api/models'
      path: '/api/models'
      fullPath: '/api/models'
      preLoaderRoute: typeof ApiModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/devices': {
      id: '/api/devices'
      path: '/api/devices'
      fullPath: '/api/devices'
      preLoaderRoute: typeof ApiDevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/output/$jobId': {
      id: '/api/output/$jobId'
      path: '/api/output/$jobId'
      fullPath: '/api/output/$jobId'
      preLoaderRoute: typeof ApiOutputJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs/$jobId': {
      id: '/api/jobs/$jobId'
      path: '/api/jobs/$jobId'
      fullPath: '/api/jobs/$jobId'
      preLoaderRoute: typeof ApiJobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiDevicesRoute: ApiDevicesRoute,
  ApiModelsRoute: ApiModelsRoute,
  ApiUploadRoute: ApiUploadRoute,
  ApiJobsJobIdRoute: ApiJobsJobIdRoute,
  ApiOutputJobIdRoute: ApiOutputJobIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
